export const FETCH_TRANSFER_INCOME = 'FETCH_TRANSFER_INCOME';
export const FETCH_TRANSFER_HISTORY = 'FETCH_TRANSFER_HISTORY';
export const ADD_NEW_TRANSFER_INCOME = 'ADD_NEW_TRANSFER_INCOME';
export const TRANSFER_APPLY = 'TRANSFER_APPLY';
export const TRANSFER_CANCEL = 'TRANSFER_CANCEL';
export const CLEAR_SEPARATED_PRODUCTS_STORAGE = 'CLEAR_SEPARATED_PRODUCTS_STORAGE';
export const FETCH_SELL_HISTORY = 'FETCH_SELL_HISTORY';
export const FETCH_SELL_PER_DAY = 'FETCH_SELL_PER_DAY';

export const TRANSFER_APPLY_ALL = 'TRANSFER_APPLY_ALL';
export const TRANSFER_CANCEL_ALL = 'TRANSFER_CANCEL_ALL';
