export const FETCH_TRANSFER_INCOME = 'FETCH_TRANSFER_INCOME';
export const ADD_NEW_TRANSFER_INCOME = 'ADD_NEW_TRANSFER_INCOME';
export const TRANSFER_APPLY = 'TRANSFER_APPLY';
export const TRANSFER_CANCEL = 'TRANSFER_CANCEL';