export const FETCH_SEPARATE_PRODUCTS = "FETCH_SEPARATE_PRODUCTS";
export const FETCH_SEPARATE_PRODUCTS_START = "FETCH_SEPARATE_PRODUCTS_START";
export const FETCH_SEPARATE_PRODUCTS_FAILURE = "FETCH_SEPARATE_PRODUCTS_FAILURE";
export const CLEAR_SEPARATED_PRODUCTS = "CLEAR_SEPARATED_PRODUCTS";

export const TRANSFER_PRODUCTS = "TRANSFER_PRODUCTS";
export const SELL_PRODUCTS = "SELL_PRODUCTS";