export const ADD_PRODUCT = "ADD_PRODUCT"
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS"

export const FETCH_PRODUCTS_SUM = "FETCH_PRODUCTS_SUM"
export const FETCH_PRODUCTS_SUM_START = "FETCH_PRODUCTS_SUM_START"
export const FETCH_PRODUCTS_SUM_FAILURE = "FETCH_PRODUCTS_SUM_FAILURE"

export const EDIT_PRODUCT = "EDIT_PRODUCT"

export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const FETCH_PLACES = "FETCH_PLACES"
export const FETCH_PLACES_START = "FETCH_PLACES_START"
export const FETCH_PLACES_FAILURE = "FETCH_PLACES_FAILURE"

export const FETCH_TYPES = "FETCH_TYPES"
export const FETCH_TYPES_START = "FETCH_TYPES_START"
export const FETCH_TYPES_FAILURE = "FETCH_TYPES_FAILURE"

export const FETCH_SIZES = "FETCH_SIZES"
export const FETCH_COLORS = "FETCH_COLORS"
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"